# With kubectl -n kafka port-forward kafka-0 9094
bases:
- ../scale-1-ephemeral
patchesStrategicMerge:
- jmx-disable.yaml
patchesJson6902:
# Currently these duplicate each others' directives to avoid an apply -k error: found conflict between different patches
- target:
    group: apps
    version: v1
    kind: StatefulSet
    name: kafka
  path: listener-localhost.json
- target:
    group: apps
    version: v1
    kind: StatefulSet
    name: kafka
  path: auto-create-topics.json
